version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run dev

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: npm run test
    depends_on:
      - app